# Generated by Django 2.1.7 on 2019-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0019_auto_20190129_1536")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="background_colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Inherit the default colour"),
                    ("bg2", "White"),
                    ("bg1", "Grey 1"),
                    ("bg3", "Grey 2"),
                    ("dark", "Dark"),
                ],
                default="",
                help_text="The background colour of your challenge pages.",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="navbar_colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Inherit the default colour"),
                    ("white", "White"),
                    ("blue2", "Blue"),
                    ("light-blue2", "Light Blue"),
                    ("purple2", "Purple"),
                    ("orange2", "Orange"),
                    ("green2", "Green"),
                    ("red2", "Red"),
                    ("dark2", "Dark"),
                ],
                default="",
                help_text="The colour of the navigation bar on your challenge pages.",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="sidebar_colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Inherit the default colour"),
                    ("white", "White"),
                    ("dark2", "Dark"),
                ],
                default="",
                help_text="The colour of the sidebar on your challenge pages.",
                max_length=5,
            ),
        ),
    ]
