# Generated by Django 2.1.7 on 2019-03-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0010_auto_20190219_1301")]

    operations = [
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="algorithm"
        ),
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="algorithm_result"
        ),
    ]
