# Generated by Django 2.1.7 on 2019-03-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mlmodels", "0001_initial"),
        ("cases", "0011_auto_20190305_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="mlmodel",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mlmodels.MLModel",
            ),
        ),
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="mlmodel_result",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mlmodels.Result",
            ),
        ),
    ]
