# Generated by Django 2.1.7 on 2019-03-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0008_auto_20190227_1500")]

    operations = [migrations.DeleteModel(name="Job")]
