# Generated by Django 2.1.7 on 2019-03-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_auto_20190305_1332"),
        ("algorithms", "0009_delete_job"),
    ]

    operations = [
        migrations.DeleteModel(name="Result"),
        migrations.RemoveField(
            model_name="algorithm", name="description_html"
        ),
        migrations.RemoveField(model_name="algorithm", name="image"),
        migrations.RemoveField(model_name="algorithm", name="image_sha256"),
        migrations.RemoveField(model_name="algorithm", name="ready"),
        migrations.RemoveField(
            model_name="algorithm", name="requires_cpu_cores"
        ),
        migrations.RemoveField(model_name="algorithm", name="requires_gpu"),
        migrations.RemoveField(
            model_name="algorithm", name="requires_gpu_memory_gb"
        ),
        migrations.RemoveField(
            model_name="algorithm", name="requires_memory_gb"
        ),
        migrations.RemoveField(
            model_name="algorithm", name="staged_image_uuid"
        ),
        migrations.RemoveField(model_name="algorithm", name="status"),
    ]
